### ISSUE TITLE
调用高德地图api查询天气时卡住

### ISSUE THREAD

**Issue by DayDreammy** [devcxl/WeChatBot#19]
![image](https://github.com/devcxl/WeChatBot/assets/107911537/fdcc509f-00f7-48ca-81f6-4581b5865a50)

报错如下，感觉是调用api超时，但是一直循环。也不能正常回答问题了
```
Traceback (most recent call last):
  File "itchat/components/register.py", line 78, in configured_reply
  File "main.py", line 81, in friend
  File "handler/text.py", line 36, in handler_text
  File "function/weather_function.py", line 45, in execute
  File "requests/api.py", line 73, in get
  File "requests/api.py", line 59, in request
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='restapi.amap.com', port=443): Max retries exceeded with url: /v3/geocode/geo?key=&address=%E6%9D%AD%E5%B7%9E (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbc6626b3d0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

2024-04-04 18:23:44,934 - httpx [INFO] HTTP Request: POST https://newapi..xyz/v1/chat/completions "HTTP/1.1 200 OK"
2024-04-04 18:25:54,160 - itchat [WARNING] Traceback (most recent call last):
  File "urllib3/connection.py", line 198, in _new_conn
  File "urllib3/util/connection.py", line 85, in create_connection
  File "urllib3/util/connection.py", line 73, in create_connection
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 793, in urlopen
  File "urllib3/connectionpool.py", line 491, in _make_request
  File "urllib3/connectionpool.py", line 467, in _make_request
  File "urllib3/connectionpool.py", line 1099, in _validate_conn
  File "urllib3/connection.py", line 616, in connect
  File "urllib3/connection.py", line 213, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fbc66276e80>: Failed to establish a new connection: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests/adapters.py", line 486, in send
  File "urllib3/connectionpool.py", line 847, in urlopen
  File "urllib3/util/retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='restapi.amap.com', port=443): Max retries exceeded with url: /v3/geocode/geo?key=ca&address=%E6%9D%AD%E5%B7%9E (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbc66276e80>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "itchat/components/register.py", line 78, in configured_reply
  File "main.py", line 81, in friend
  File "handler/text.py", line 36, in handler_text
  File "function/weather_function.py", line 45, in execute
  File "requests/api.py", line 73, in get
  File "requests/api.py", line 59, in request
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='restapi.amap.com', port=443): Max retries exceeded with url: /v3/geocode/geo?key=&address=%E6%9D%AD%E5%B7%9E (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbc66276e80>: Failed to establish a new connection: [Errno 110] Connection timed out'))

2024-04-04 18:25:55,700 - httpx [INFO] HTTP Request: POST https://newapi..xyz/v1/chat/completions "HTTP/1.1 200 OK"

```

**Comment by devcxl** [comment]
这个应该是网络问题导致的，后续我会把插件报错处理下，你用手机退出登陆，再重启docker登陆应该就不卡循环了

**Comment by DayDreammy** [comment]
> 这个应该是网络问题导致的，后续我会把插件报错处理下，你用手机退出登陆，再重启docker登陆应该就不卡循环了

ok。
有没有一种可能，我的vps被ban了？我部署了newapi，然后openai的渠道都是通的，国内大模型的渠道没一个通的。

**Comment by devcxl** [comment]
我感觉是你vps网络问题或者是高德把你vps的ip禁了（如果你机器在国外这个可能性还是很高的）
